<?xml version="1.0"?>
<package format="3">
  <name>vt_vive_tracker_gui</name>
  <version>0.2.0</version>
  <description>Standalone GUI for VIVE Ultimate Tracker visualization.</description>
  <maintainer email="vision-tactile@example.com">Vision Tactile Team</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <depend>geometry_msgs</depend>
  <depend>rclpy</depend>
  <depend>vt_tracker_msgs</depend>
  <depend>vt_vive_tracker</depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>python3-tk</exec_depend>
  <test_depend>python3-pytest</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
